version: "3.8"

services:
  pgalejandro:
    image: 127.0.0.1:5001/pgmaldonado:1.0.1
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgmaldonado.entrypoints=http"
        - "traefik.http.routers.pgmaldonado.rule=Host(pgmaldonado.byronrm.com)"
        - "traefik.http.middlewares.pgmaldonado-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.pgmaldonado.middlewares=pgmaldonado-https-redirect"
        - "traefik.http.routers.pgmaldonado-secure.entrypoints=https"
        - "traefik.http.routers.pgmaldonado-secure.rule=Host(pgmaldonado.byronrm.com)"
        - "traefik.http.routers.pgmaldonado-secure.tls=true"
        - "traefik.http.routers.pgmaldonado-secure.tls.certresolver=http"
        - "traefik.http.routers.pgmaldonado-secure.service=pgmaldonado"
        - "traefik.http.services.pgmaldonado.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true